version: '3.9'

services:
  db:
    restart: always

    image: postgres:13

    container_name: defender_society_db

    volumes:
      - db_data:/var/lib/mysql

    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"

    networks:
      - backend

  redis:
    restart: always
    image: redis
    container_name: defender_society_redis
    networks:
      - backend


  app:

    restart: always
    build:
        context: ./defender_society

    container_name: django

    volumes:
      - static_data:/vol/web/static
      - static_data:/vol/web/media
      - static_data:/vol/web/whoosh_index

    ports:
      -  "8000:8000"
    expose:
      -  "8000"
    environment:
      defender_society_POSTGRES_USER: "${defender_society_POSTGRES_USER}"
      defender_society_POSTGRES_NAME: "${defender_society_POSTGRES_NAME}"
      defender_society_POSTGRES_PASSWORD: "${defender_society_POSTGRES_NAME}"
      defender_society_SECRET_KEY: "${defender_society_SECRET_KEY}"
      defender_society_POSTGRES_HOST: db
      defender_society_POSTGRES_PORT: 5432
      defender_society_REDIS_HOST: redis
      defender_society_REDIS_PORT: 6379

    depends_on:
       - db
       - redis

    networks:
        - backend
        - frontend

  proxy:
      build:
         context: ./nginx

      volumes:
        - static_data:/vol/static
        - static_data:/vol/media
      networks:
        - frontend
      ports:
        - "80:80"
      depends_on:
        - app

volumes:
  db_data:
  static_data:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

