# Generated by Django 2.2.20 on 2021-04-10 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='About content')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='modification time')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Article title')),
                ('summary', models.TextField(default='The article summary is equivalent to the content of the web page description, please be sure to fill in...', max_length=230, verbose_name='Article summary')),
                ('body', models.TextField(verbose_name='Article content')),
                ('img_link', models.CharField(default='/ static/blog/img/summary.png ', max_length=255, verbose_name='picture address')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='modification time')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
                ('slug', models.SlugField(unique=True)),
                ('is_top', models.BooleanField(default=False, verbose_name='top')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Article',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Number determines the order in which pictures are played, no more than 5 pictures', verbose_name='Number')),
                ('title', models.CharField(blank=True, help_text='title can be empty', max_length=20, null=True, verbose_name='title')),
                ('content', models.CharField(max_length=80, verbose_name='Description')),
                ('img_url', models.CharField(max_length=200, verbose_name='picture address')),
                ('url', models.CharField(default='#', help_text='Hyperlink to the picture jump, default # means no jump', max_length=200, verbose_name='Jump link')),
            ],
            options={
                'verbose_name': 'Picture Carousel',
                'verbose_name_plural': 'Picture Carousel',
                'ordering': ['number', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Article Category')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(default='Alumni Association blog for Big Brothers Big Sisters of Kentuckiana', help_text='Used as description in SEO, length refers to SEO standard', max_length=240, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Classification',
                'verbose_name_plural': 'Classification',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='article keywords')),
            ],
            options={
                'verbose_name': 'Keywords',
                'verbose_name_plural': 'Keywords',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='newsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Shared Article Title')),
                ('summary', models.CharField(max_length=150, verbose_name='Shared Article Summary')),
                ('hyperlink_address', models.CharField(default='#', help_text='Hyperlink for the articles listed, default # means no jump', max_length=200, verbose_name='Hyperlink')),
            ],
            options={
                'verbose_name': 'Shared Articles',
                'verbose_name_plural': 'Shared Articles',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='RequirementsBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Requirements')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='modification time')),
            ],
            options={
                'verbose_name': 'Requirements',
                'verbose_name_plural': 'Requirements',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='article tag')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(default='Alumni Association blog for Big Brothers Big Sisters of Kentuckiana', help_text='Used as description in SEO, length refers to SEO standard', max_length=240, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'label',
                'verbose_name_plural': 'label',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EventMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Event')),
            ],
        ),
    ]
