# Generated by Django 2.2.20 on 2021-04-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210410_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img_link',
            field=models.CharField(default='/static/blog/img/summary.png', max_length=255, verbose_name='picture address'),
        ),
    ]
